### ISSUE TITLE
OTU representative sequences for the Ravel task

### ISSUE THREAD

**Issue by jonathanishhorowicz** [knights-lab/MLRepo#5]
Hi,

Thank you for this excellent resource! 

Are the representative sequences for each OTU available for the Ravel set of tasks? The processed sequences that are provided in the fastq file do not seem to correspond to any of the OTUs as they have names like 

```>SRR063057_0 SRR063057.1 FU604JZ01CTHV2 length=228```

which correspond to the sample IDs (SRR063057 is a sample ID).

Thank you in advance!

**Comment by pvangay** [comment]
Hi @jonathanishhorowicz, the processed fastq files do not typically contain any information about the OTUs (these are input files before you start the clustering step). You'll want to take a look at the OTU files ([here](https://github.com/knights-lab/MLRepo/blob/master/datasets/ravel/refseq/otutable.txt) and [here](https://github.com/knights-lab/MLRepo/blob/master/datasets/ravel/gg/otutable.txt)) - you should be able to find all of the OTU IDs in the first column. Each of these IDs correspond to IDs that exist within green genes 97 or the NCBI RefSeq db - those are public files that you should be able to access directly (you should be able to search based on these IDs to grab the corresponding representative sequences).

Sorry I don't have this readily available for you as it has been some time since I've accessed this project (and no longer have access to the super computer). Hope this helps!
